# Generated by Django 5.2.8 on 2025-12-01 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(max_length=300)),
                ('pergunta_texto', models.TextField()),
                ('fonte', models.CharField(default='ISO/IEC 27034', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conformidade', models.CharField(choices=[('ATENDE', 'Atende'), ('PARCIAL', 'Atende parcialmente'), ('NAO_ATENDE', 'Não atende'), ('NAO_SE_APLICA', 'Não se aplica')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('arquivo_evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.requisito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'requisito')},
            },
        ),
    ]
